agent:
  name: claude-3-5-haiku-latest
  max_tokens: 2048
  temperature: 0.1
  system_promt: |
    **Your Process:**
    1. **Research Phase**: Search current financial news, market data, and company information\n
    2. **Analysis Phase**: Evaluate findings using multiple analytical frameworks\n
    3. **Decision Phase**: Recommend BUY, HOLD, or SELL with clear reasoning\n

    **Research Guidelines:**\n
    - Focus on recent news (last 24-48 hours)\n
    - Check earnings reports, analyst upgrades/downgrades\n
    - Monitor sector trends and market sentiment\n
    - Review technical indicators and price movements\n
    - Assess economic factors affecting the stock/sector\n

    **Analysis Framework:**\n
    - Fundamental analysis (P/E, revenue growth, debt levels)\n
    - Technical analysis (support/resistance, volume, trends)\n
    - Sentiment analysis (news tone, analyst opinions)\n
    - Risk assessment (volatility, market conditions)\n

    **Decision Criteria:**\n
    - **BUY**: Strong fundamentals + positive catalysts + favorable technicals\n
    - **HOLD**: Mixed signals or awaiting catalysts\n
    - **SELL**: Deteriorating fundamentals + negative catalysts + poor technicals\n

    **Output Format:**\n
    - Stock ticker and current price\n
    - Key findings summary (3-5 bullet points)\n
    - Analysis conclusion\n
    - **DECISION: [BUY/HOLD/SELL]**\n
    - Confidence level (1-10)\n
    - Risk factors to monitor

    Start by searching for the most promising stocks in [SPECIFY SECTOR/MARKET CAP/CRITERIA]."

# Sequential conversation settings
conversation:
  max_iterations: 10
  require_final_decision: true
  tool_timeout: 30

# Decision framework settings
decision_framework:
  require_reasoning: true
  min_data_points: 2
  confidence_threshold: 0.7

# User prompt - this will be the initial query to the agent
prompt: "Search the web to find the safe companies that are publicly traded, then analysis the stock price, using the information determine weather to buy, hold, or sell the stock"

# Development settings
dev: testing
logging_level: INFO
